### ISSUE TITLE
Font size of code to large?

### ISSUE THREAD

**Issue by ehmkah** [frjo/hugo-theme-zen#1]
If I write a text in an unordered list which has code in it like 

    * `Application` - in an unordered list

 it will be rendered correctly to monospace, but the font size looks too large. If I do it in normal text, it looks good. See screenshot
![screen shot 2017-05-21 at 07 31 41](https://cloud.githubusercontent.com/assets/6233328/26281464/9a69854e-3df7-11e7-924e-2a6008e66f85.png)

Problems occurs under all browser in Mac OSX. 

Could it be fixed? Maybe something like 0.9em or 0.8em for monospace?

**Comment by frjo** [comment]
Believe I have fix that in #c6473f72a18a4d154fdc34ba66dbf5795e424770

I'm migrating my own blog to Hugo (and this theme) so making a lot of changed/additions now.

**Comment by ehmkah** [comment]
Thank you. Looks good now. 👍
