### ISSUE TITLE
List template assumes pages have titles

### ISSUE THREAD

**Issue by gabrc52** [frjo/hugo-theme-zen#101]
See [layouts/_default/summary.html](https://github.com/frjo/hugo-theme-zen/blob/main/layouts/_default/summary.html):

`<a href="{{ .RelPermalink }}">{{ .Title }}</a>`

Since the only way to open that page is through that link, if there is no title, the link is invisible.

**Comment by frjo** [comment]
Thanks for the contribution! This feels like an edge case and the templates are easy to override for the few that needs this.

I have build many Hugo sites with the Zen theme and never encountered one where there was no titles.
