### ISSUE TITLE
Value4value support

### ISSUE THREAD

**Issue by metasikander** [frjo/hugo-theme-zen#109]
Hello. Hope everything is well and you have a great holliday.
I was wondering if it would be a lot of work to add support for Value for Value with your theme?
here's the xml tags that is needed (provided by podcastindex.org). This assumes no split:

```xml
<podcast:value type="lightning" method="keysend" suggested="0.00000005000"> 
    <podcast:valueRecipient name="[ Name of reciever ]" type="node" address="[ lnurl ]" customKey="[ custom key from v4v provider ]" customValue="[custom value from v4v provider] split="100" /> 
</podcast:value>
```

**Comment by metasikander** [comment]
if you don't want to add this, could i get a pointer to what i need to do to add it myself?

**Comment by frjo** [comment]
Override this file and add the above tags:

https://github.com/frjo/hugo-theme-zen/blob/main/layouts/podcast/rss.xml

**Comment by metasikander** [comment]
great that worked! thank you

my solution for reference: https://github.com/metasikander/antihashed/blob/main/layouts/podcast/rss.xml
