### ISSUE TITLE
[Suggestion] Bump Hugo Version and Rename the config file

### ISSUE THREAD

**Issue by fyordsvat** [frjo/hugo-theme-zen#115]
1. Hugo renamed the config file from`config` to `hugo` in version 0.110.0
2. The deprecation of `.Site.Author` was done in v.0.120.0 #114 

I see you already have an intent to [bump the Hugo version](https://github.com/frjo/hugo-theme-zen/issues/113#issuecomment-2172572185).

**Comment by frjo** [comment]
Yes, might be time to bump the min supported version.

**Comment by frjo** [comment]
I have bumped min version to 0.124.0 now.
