### ISSUE TITLE
Author data in site config is not formatted correctly in a post

### ISSUE THREAD

**Issue by georgew509** [frjo/hugo-theme-zen#117]
I created a new site and installed the Zen theme. I added my Author info to the site config:

```
params:
  author:
    name: "George Wilder"
```

What I see  for that Author line in the Post summary and the Post:

map[name:George Wilder] - December 12, 2023

If I define the author in the post front matter:
author: "George Wilder"

it works fine (no map[]).

Did I do something wrong or is this an issue with the theme?

**Comment by frjo** [comment]
I believe this issue is fixed in v4. See https://github.com/frjo/hugo-theme-zen/releases

The changes from v3 to v4 is not that big. The big difference is that v4 now requires Hugo v0.124 or later.

**Comment by georgew509** [comment]
I thought that I was using the latest Zen version?Yesterday, I cloned a fresh copy:git clone https://github.com/frjo/hugo-theme-zen.git themes/zenI also was using the latest Hugo release.GeorgeOn Nov 6, 2024, at 1:19 AM, Fredrik Jonsson ***@***.***> wrote:﻿
I believe this issue is fixed in v4. See https://github.com/frjo/hugo-theme-zen/releases
The changes from v3 to v4 is not that big. The big difference is that v4 now requires Hugo v0.124 or later.

**Comment by frjo** [comment]
You found a bug. I was using `$.Param "author"` that will fall back to the global params if the page param does not exist. Have replaced it with `.Params.author` now.

Please test the latest code and report back if it work for you. If it does I will make a new release.

Thanks for reporting this!

**Comment by georgew509** [comment]
On Nov 6, 2024, at 8:31 AM, Fredrik Jonsson ***@***.***> wrote:
> 
> Please test the latest code and report back if it work for you. If it does I will make a new release.

That fixed the issue. Thanks for the quick turn around!!

**Comment by frjo** [comment]
New release with fix out now.

https://github.com/frjo/hugo-theme-zen/releases/tag/v4.2.0
