### ISSUE TITLE
Using figure shortcode for non /static images

### ISSUE THREAD

**Issue by pioorg** [frjo/hugo-theme-zen#13]
Hi

I'm not sure it's the best place to ask/suggest this.
When using the figure shortcode in "plain" Hugo, the images can also come from the page bundles, i.e. they can be next to index.md file. With the figure shortcode from the Zen theme that's impossible, because: `{{ with (imageConfig (add "/static/" (.Get "src"))) -}}`, so the images are meant to be stored in static only.
Could this be relaxed somehow, so something like this: https://alison.rbind.io/post/2019-02-21-hugo-page-bundles/ works?

Thanks
P.

**Comment by frjo** [comment]
@pioorg Working on a fix for this.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
@pioorg If you have time can you test https://github.com/frjo/hugo-theme-zen/pull/14 and see if it works well?

**Comment by pioorg** [comment]
Hi @frjo

If you mean the branch `feature/figure-shortcode-page-resources`, then it it worked for me.

**Comment by frjo** [comment]
@pioorg Thanks for testing. This is now merged.
