### ISSUE TITLE
Issue building a site on AWS Amplify

### ISSUE THREAD

**Issue by k0a8t1o6** [frjo/hugo-theme-zen#16]
Using this theme as a submodule of mine, when deploying the site using AWS Amplify I often encountered build error as following.

`[WARNING]: Error: "/codebuild/output/src721358463/src/SITENAME/themes/zen/layouts/shortcodes/figure.html:18:1": parse failed: template: shortcodes/figure.html:18: illegal number syntax: "-"`. And the error is followed by failure messages.
2020-06-15T12:01:21.770Z [ERROR]: !!! Build failed
2020-06-15T12:01:21.841Z [ERROR]: !!! Non-Zero Exit Code detected

**Comment by frjo** [comment]
Never seen that on local build and I have not used AWS Amplify.

Does the built in Figure shortcode work without errors?

Can you try to remove all the "-" signs I have in the template tags to avoid unneeded whitespace?

**Comment by k0a8t1o6** [comment]
If I build it on local machine it works fine. This only occurs in AWS Amplify.
Correct me if I am wrong, to remove "-" signs from the shortcode, would I need to fix public repository since this is loaded as submodule? AWS loads repo from a GitHub repository.

**Comment by frjo** [comment]
You can make a copy of the figure shortcode, edit it and place it in you projects "layout/shortcodes" directory.
