### ISSUE TITLE
Light house Issue Not 100%

### ISSUE THREAD

**Issue by domaingood** [frjo/hugo-theme-zen#20]
Performance
Best Practices
Serves images with low resolution
SEO
Document does not have a meta description
SEO
Tap targets are not sized appropriately
Accessibility
Heading elements are not in a sequentially-descending order
Accessibility
Links do not have a discernible name

**Comment by frjo** [comment]
What page do you test on? When I run on e.g my own blog https://xdeb.org/ that uses this theme I get 100%.

Another site that uses this theme is https://www.bypasscensorship.org/ and that does not get a full score but that is due to images etc. on the site, not the theme.

**Comment by domaingood** [comment]
Thank you for quick reply https://web.dev/measure/ 
I tested Demo https://themes.gohugo.io/theme/hugo-theme-zen/

**Comment by frjo** [comment]
Will see if I can get the demo site to look better. Seems to not works well with Zen theme auto menu.
