### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by ctsdownloads** [frjo/hugo-theme-zen#21]
Loving the search engine feature, would love to get a better idea how to create a working search box in the menu? The search feature is outstanding, but going to a webpage to search isn't ideal. Is there a way to activate a search box instead of a dedicated page?

Thanks :)

**Comment by frjo** [comment]
Set the "searchform" parameter to true in your config file, then the search javascript will be added to every page.

Then see the shortcode "search.html" for the html to add to your menu/header.

**Comment by ctsdownloads** [comment]
Sounds simple enough, I'll give it a go tomorrow. Thanks for the quick reply.
