### ISSUE TITLE
hugo server Error

### ISSUE THREAD

**Issue by domaingood** [frjo/hugo-theme-zen#22]
hugo server
Building sites … WARN 2020/07/14 23:26:47 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
ERROR 2020/07/14 23:26:47 TOCSS: failed to transform "sass/print.scss" (text/x-scss): resource "scss/sass/print.scss_6f664080c634a8edb051ceda3df60601" not found in file cache
Built in 42 ms
Error: Error building site: TOCSS: failed to transform "sass/styles.scss" (text/x-scss): resource "scss/sass/styles.scss_c253c1450adff31bb2ccb2afd691b09e" not found in file cache

**Comment by frjo** [comment]
Never seen this on the sites I build with the Zen theme.

Can you post a link to a repo or recreate it with an example site in a public repo?

**Comment by jwarner112** [comment]
I've been getting this problem as well:

```
~/code/HUGO/xyzzy/themes/zen/exampleSite  hugo server --themesDir ../..
Building sites … ERROR 2020/07/21 15:34:26 TOCSS: failed to transform "sass/styles.scss" (text/x-scss): resource "scss/sass/styles.scss_c253c1450adff31bb2ccb2afd691b09e" not found in file cache
ERROR 2020/07/21 15:34:26 TOCSS: failed to transform "sass/print.scss" (text/x-scss): resource "scss/sass/print.scss_6f664080c634a8edb051ceda3df60601" not found in file cache
Built in 34 ms
Error: Error building site: TOCSS: failed to transform "sass/mobile.scss" (text/x-scss): resource "scss/sass/mobile.scss_4b3618896c13c1af159e65083abb6447" not found in file cache
```

I'm brand-new to Hugo and apparently some big changes happened recently that have been breaking themes? I'd given up on this theme as broken and moved on, when I found an article about breakage in a different theme which mentioned that Hugo Extended was a requirement. I've gleaned that plain Hugo lacks full sass/scss support or something?

Anyway I tried it and now the example site is building just fine.

broken with Hugo `0.74.2 64-bit Linux` release, but works with the identical `-extended` release.

I recommend adding Extended as a requirement. And as a rider, I recommend also modifying your documentation's `Run example site` section with a more complete (absolute-pathed) snippet:


Run example site
---

To run the embedded demo (`themes/zen/exampleSite`):

```
hugo server --source "/path/to/hugo/project/themes/zen/exampleSite" --themesDir "../.."
```

Note that if you use a relative path for `--themesDir`, it will be relative to the path given for `--source`, the default for which is your current directory if no others are provided.

**Comment by frjo** [comment]
Yes, Hugo Extended is required. It's the default on most plattforms I believe.
