### ISSUE TITLE
Theme lacks support for Google Analytics

### ISSUE THREAD

**Issue by Rahul147** [frjo/hugo-theme-zen#24]
The theme looks (and feels?) good and is minimal, sadly doesn't support google analytics; this is bummer since user demography plays an important role while blogging (also other analytical tools - page views etc.)

Is it possible to support google analytics out of the box? Please let me know if you'd be interested in such a pull request.

Note: There is a work around to it - by adding custom scripts. Would prefer if it supports google analytics "out of the box".

**Comment by frjo** [comment]
If you can implement it in the same way as Matomo is done I can merge it in to the Zen theme.

To have it work with Content security policy headers see my blog post https://xdeb.org/post/2020/01/14/content-security-policy-headers-when-using-matomo-or-google-analytics/#google-analytics

**Comment by frjo** [comment]
And glad you like the theme!
