### ISSUE TITLE
How to use KaTex with this theme?

### ISSUE THREAD

**Issue by maxdrohde** [frjo/hugo-theme-zen#29]
Is it possible to use KaTex with this theme? If so, would you show how to configure it?

Thank you,
Max

**Comment by maxdrohde** [comment]
I see now that it is possible here: https://themes.gohugo.io//theme/hugo-theme-zen/post/math-typesetting/

If someone could show how to enable it, that would be much appreciated.

**Comment by frjo** [comment]
The Hugo Coder theme has built in support for math. You can use that theme instead or implement their solution in the Zen theme. If you make a PR for it we can add math support to Zen.

https://github.com/luizdepra/hugo-coder/blob/9ca430610e37fd7248d68bf43cb667fdd6f2912c/layouts/partials/posts/math.html

**Comment by maxdrohde** [comment]
I will look into the Hugo Coder theme -- thank you.
