### ISSUE TITLE
Customize Fonts

### ISSUE THREAD

**Issue by fri-sch** [frjo/hugo-theme-zen#3]
Hi,

I'm checking out this theme and I'm wondering what's the best way to customize things like fonts. For example I want to use a different font family for the body text.

Is there a way to customize the SASS variables on the project level? I tried copying `_variables.scss` to `assets/sass/, but that doesn't seam to work.

Thanks!

**Comment by frjo** [comment]
You need to replicate the complete assets path. Make it `/assets/init/_variables.scss` and it should work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fri-sch** [comment]
Doh! You're right, I just missed one directory level. Thanks for pointing this out so fast!
