### ISSUE TITLE
Please add support for menu.shortcuts

### ISSUE THREAD

**Issue by marcin-chwedczuk** [frjo/hugo-theme-zen#30]
Say I have my home page generated using Hugo+Zen on `foo.bar` but for my blog I use Jekyll and GitHub pages + custom domain. In short I have my blog at `blog.foo.bar`. Now I would like to add a menu item to link to my blog but I cannot do this. When I add `[[menu.main]]` pointing to my blog the autogenerated entries no longer appear in the menu. On the other hand the syntax `[[menu.shortcuts]]` is also not supported.

My workaround for now is to hack `menu.html` (I added this after `Site.Sections`):
```html
{{ if .Site.Menus.shortcuts -}}
{{ range .Site.Menus.shortcuts -}}
<li><a href="{{ .URL | relLangURL }}">{{ .Name }}</a></li>
{{ end -}}
{{ end -}}
```
And in `config.toml`:
```
[[menu.shortcuts]]
name = "Programming Blog"
identifier = "blog"
url = "https://marcin-chwedczuk.github.io/"
weight = 0
```

This will not generate a proper mobile menu - I guess I need to hack more...

It would be good to have support for shortcuts included out of the box. Even better if we could support it with `weights` field so that both shortcuts and autogenerated menu entries could be mixed.

**Comment by frjo** [comment]
Is not "menu.shortcuts" simply a menu that happens to be named "shortcuts"? Can you point me to any documentation of it?

If you want to change how the menus are built there is no need to hack the theme files. Instead copy ^themes/zen/layouts/partials/menu.html` too `layouts/partials/menu.html` and make your changes there.

**Comment by frjo** [comment]
And glad you found the Zen theme useful!

**Comment by marcin-chwedczuk** [comment]
> And glad you found the Zen theme useful!
It's me who should be thankful for your work! 🙇‍♂️ 

Returning to the problem. I admit that I only skimmed Hugo docs. I just wanted to add an extra item to the main menu so I google "how to add extra menu item Hugo" and got an advice to put extra menu entry into `config.toml`:
```
 [[menu.main]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
```
(source: https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu)

The result was, of course, that I got only this menu entry. All other entries for About, Home and Search disappeared. OK I started googling (without giving it much tough why it is not working) and found this site: https://learn.netlify.app/en/cont/menushortcuts/ I just pasted the code posted there and it didn't work again. Now I understand that "Learn Theme for Hugo" is a name of test theme, I didn't notice it earlier and I though that this is a general advice...

IMHO I think this is pretty common use-case and it would be good to support it out of the box. But of course you have the final word here...

**Comment by frjo** [comment]
Now I see, the menu shortcuts are a feature of the Hugo Learn theme http://github.com/matcornic/hugo-theme-learn. 

I suggest you define the menus in the config file for the non content part and for content in the front matter. That what I do for all but the most simple sites. 

The auto menu feature in the Zen theme is there so users see some menu out of the box.
