### ISSUE TITLE
Logo Not Changing

### ISSUE THREAD

**Issue by Hakeemmidan** [frjo/hugo-theme-zen#31]
Hi Fredrik,

Thank you for creating this theme

I tried changing the logo of my website but it doesn't seem to work. The default theme logo is still showing

I followed `README.md` instructions and have my logo relative path as `static/images/logo.png`. ( It's also present under `public` directory and has the following relative path `public/images/logo.png`.)

Though this shouldn't change anything, I also tried changing `logo` flag in `config.toml` to `true`, and that didn't work too

I don't think I changed anything in `baseof.html`, but here it is just for safety:
```HTML
<!DOCTYPE html>
<html class="nojs" lang="{{ .Site.Language.Lang }}" dir="{{ .Site.Language.LanguageDirection | default "ltr" }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">

<title>{{ block "title" . }}{{ .Title }} – {{ .Site.Title }}{{ end }}</title>
{{ partial "meta.html" . }}
{{ partialCached "styles.html" . }}
{{- block "head" . }}{{ end }}
{{ partial "meta_json_ld.html" . }}
{{ partial "scripts.html" . }}
{{ partialCached "tracking.html" . }}
</head>

<body class="{{ if .IsPage }}single-page{{ else }}list-page{{ end }}{{ if .IsHome }} front{{ end }}">
<div class="page layout__page{{ if $.Param "sidebar" | default true }} layout__sidebar-second{{ end }}">
<header class="header layout__header">
{{ if $.Param "logo" | default true }}<a href="{{ "/" | relLangURL }}" title="Home" rel="home" class="header__logo"> <img src="{{ "/images/logo.png" | relURL }}" alt="Home" class="header__logo-image"></a>{{ end }}
<h1 class="header__site-name">
<a href="{{ "/" | relLangURL }}" title="Home" class="header__site-link" rel="home"><span>{{ .Site.Title }}</span></a>
</h1>
<div class="region header__region">
{{ if .Site.IsMultiLingual }}{{ partial "language-selector.html" . }}{{ end -}}
</div>
</header>

{{ partial "menu.html" . }}

{{ block "main" . }}{{ end }}

{{ if $.Param "sidebar" }}{{ partial "sidebar.html" . }}{{ end -}}

<footer class="footer layout__footer">
{{ if $.Param "feedlinks" }}{{ partial "feedlinks.html" . }}{{ end -}}
<p>{{ with $.Param "copyright" }}{{ . | markdownify }}{{ else }}<span>© {{ .Site.Title }}</span>{{ end }}</p>
{{ with $.Param "footer" }}<p>{{ . | markdownify }}</p>{{ end }}
{{ if $.Param "poweredby" }}<p>Powered by <a href="https://gohugo.io/">Hugo</a> and the <a href="https://github.com/frjo/hugo-theme-zen">Zen theme</a>.</p>{{ end }}
</footer>

</div>
{{ if $.Param "mobilemenu" }}{{ partial "mobilemenu.html" . }}{{ end -}}
</body>
</html>

```

PS: Changing the value of `logo.png` in `baseof.html` to something other than `logo.png` (e.g. `custom_logo.png`), and having the same file name under `static/images` fixes it, but I don't think that's the right approach since it requires changing around the theme template

Looking forward to your response
Cheers,
Hakeem

**Comment by frjo** [comment]
Most likely a browser cache issue, do a hard reload and it should sort itself out.

Make also sure that the copy in `public/images/logo.png` really is the new logo.

**Comment by Hakeemmidan** [comment]
Yes, I think it was a browser cache issue. Seems fine today; cache must've cleared itself out. Opened in different browser to confirm and it seems to work there as well. (`public/images/logo.png` was new logo. )

Thank you 🙏

**Comment by frjo** [comment]
Glad you got it working.
