### ISSUE TITLE
Fails to work with hugo quickstart guide

### ISSUE THREAD

**Issue by gregates** [frjo/hugo-theme-zen#32]
Tried to create a new static site with hugo today, following the [quickstart guide](https://gohugo.io/getting-started/quick-start/). I followed the steps in that guide exactly, with the exception of choosing the zen theme.

When I got to [Step 3: Add a Theme](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme), I clicked through to [themes.gohugo.io](https://themes.gohugo.io/) and saw the #2 theme in the list was Zen. It looked nice, so I installed it instead of the suggestion in the quick start guide, using the following commands:

```
cd quickstart
git init
git submodule add https://github.com/frjo/hugo-theme-zen.git themes/zen
echo 'theme = "zen"' >> config.toml
```

However, then [Step 5: Start the Hugo server](https://gohugo.io/getting-started/quick-start/#step-5-start-the-hugo-server) failed with the following error message:

```
$  hugo server -D
Start building sites …
WARN 2020/11/14 23:23:39 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
ERROR 2020/11/14 23:23:39 TOCSS: failed to transform "sass/print.scss" (text/x-scss): resource "scss/sass/print.scss_6f664080c634a8edb051ceda3df60601" not found in file cache
Built in 11 ms
Error: Error building site: TOCSS: failed to transform "sass/styles.scss" (text/x-scss): resource "scss/sass/styles.scss_c253c1450adff31bb2ccb2afd691b09e" not found in file cache
```

I installed

```
$ hugo version
Hugo Static Site Generator v0.78.2-959724F0 linux/amd64 BuildDate: 2020-11-13T10:08:14Z
```

and I'm doing this on an Ubuntu 18.04 install on WSL2:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ uname -r
4.19.128-microsoft-standard
```

If, instead, I use the theme suggested in the quick start guide, the server starts successfully, so I suspect it was my choice of theme that was the issue.

**Comment by frjo** [comment]
The Zen theme need the extended version of Hugo. 

That version has the Sass support and is the one most users should install.

**Comment by frjo** [comment]
And glad you found the Zen theme interesting!
