### ISSUE TITLE
Podcast fails when using CDN

### ISSUE THREAD

**Issue by marvi** [frjo/hugo-theme-zen#37]
In  layouts/podcast/rss.xml is trying to stat the file even if a CDN is configured:
 
`{{ with .Params.podcast.mp3 }}{{ $file_stat := os.Stat (add "/static" (. | relURL)) }}<enclosure url="{{ if $.Site.Params.Podcast.cdn }}{{ add $.Site.Params.Podcast.cdn (. | relURL) }}{{ else }}{{ . | absURL }}{{ end }}" length="{{ $file_stat.Size }}" type="audio/mpeg" />{{ end }} `

`error calling Stat: LStat content/static/ep1.mp3: file does not exist`

If I remove the call to stat and the `length` attribute it works as intended.

**Comment by frjo** [comment]
Thanks for the report. That is a bug. Will try to get that fixed.

**Comment by frjo** [comment]
When I have used a CDN för audio files the origin was always my own server. This is not the case for you, I assume you upload your audio files to another service.

I have added a new podcast parameter "local". It defaults to true but you can set it to false, indicating that you have your audio files on a remote location.

https://github.com/frjo/hugo-theme-zen/commit/117ca0ef9f8cd956843b8a27d0c328e8c1cf3c77

**Comment by marvi** [comment]
That should work. Thanks.
