### ISSUE TITLE
list-style-type can't be overridden?

### ISSUE THREAD

**Issue by marvi** [frjo/hugo-theme-zen#38]
This is probably my fault, but I have exhausted my Google-fu and imagination. :) 

I can't get `list-style-type` to be honored. I have tried `_custom.scss` and even style attribute in HTML. 

1. Allow unsafe HTML in config.yaml
2. Add an HTML list in about.md:

```html
<ul>
<li style="list-style-type:none; color:green;">Foo</li>
<li>Bar</li>
</ul>
```

3. First list item is green, but the circle is visible. I had expected it to not show. 

Is there some !important setting in the sass code making it impossible to override?

**Comment by frjo** [comment]
Create a **empty** `_zen.scss` next to your `_custom.scss` and see if that fixes it. Besides the zen styles there is only very boiler plate stuff.

You can view and search all styles here https://github.com/frjo/hugo-theme-zen/tree/main/assets/sass

**Comment by marvi** [comment]
Thanks, I tracked it down. 

`components/list-straight-left/_list-straight-left.scss`

It replaces the circle with a custom placed character. 

```
%ul-straight-left {
  display: table;
  list-style: none;
  padding: 0;

  & > li {
    display: table-row;

    &::before {
      @include font-size(s);
      @include padding-right(.5);
      display: table-cell;
      content: '\2022';

      @include respond-to(xxl) {
        @include font-size(s-2);
      }
    }
  }
}
```
