### ISSUE TITLE
Sidebar lists all the posts on the site

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#39]
If you enable the sidebar in the hugo config. The side displays all the published posts. I don't think there is way to limit the lists to latest 10 posts.

**Comment by frjo** [comment]
The default sidebar only works for small sites. I do a number of them so in many cases I find it useful.

For other sites I override the sidebar partial with something that suites that site.

**Comment by arky** [comment]
Thanks @frjo Overrided the sidebar by limiting the posts to 10 with `range first 10 .Pages` as advised.
