### ISSUE TITLE
Don't display dates on tags

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#40]
When you set 'submitted: true' dates are displayed on /tags/ page. 
![image](https://user-images.githubusercontent.com/808895/110846217-1add6680-82de-11eb-8f0f-77638e568b02.png)

**Comment by frjo** [comment]
Indeed they do, must confess I never look at this page.

You can create custom templates for "taxonomy", until then the default list/single etc. templates are used.

See https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-taxonomy-pages

**Comment by frjo** [comment]
If you come up with something you think others would find useful please create a PR.

**Comment by arky** [comment]
Am just picking up go and hugo. Would be happy to send in a PR.

**Comment by frjo** [comment]
Excellent! Glad you found the Zen theme interesting.
