### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Skarlso** [frjo/hugo-theme-zen#43]
Hello!

Complete noob here to designing things. :) Is there a possibility to have a dark mode? Or do you happened to have a CSS lying around somewhere maybe for that? Pretty please? :))

Thanks!

**Comment by frjo** [comment]
I do not use dark mode myself so have no CSS for that. 

As the Zen theme is a base theme it would not be that useful I think. Most users of the theme I assume add their own CSS to it.

**Comment by Skarlso** [comment]
Yeah, that makes sense of course. I'll try creating one then. :) I'm sure there are plenty posts about it. :) Thanks anyways!
