### ISSUE TITLE
Theme demo broken on Hugo Themes Showcase 

### ISSUE THREAD

**Issue by onedrawingperday** [frjo/hugo-theme-zen#5]
Hello @frjo 

Currently your theme's demo does not generate as mentioned in https://github.com/gohugoio/hugoThemes/issues/669#issuecomment-518648215

To fix you need to change [line 8](https://github.com/frjo/hugo-theme-zen/blob/master/theme.toml#L8) of `theme.toml` to: `min_version = "0.55.0"`

The `min_version` needs to be a string.

Feel free to close this issue once you do the above

Also note that once gohugoio/hugoThemes#668 is addressed you will need to keep an eye on whether the Zen theme demo generates on the Hugo website.

We are a very small team and we just cannot keep up opening issues in the various theme repositories. Whenever a theme demo breaks and remains broken then at some point it will be removed from the list without prior warning.

Thank you.

cc: @digitalcraftsman

**Comment by frjo** [comment]
@onedrawingperday Thank you for alerting me of this! I have committed a fix now.
