### ISSUE TITLE
sidebar: false - but still room for it

### ISSUE THREAD

**Issue by mortenkjarulff** [frjo/hugo-theme-zen#50]
Hi,

I am running with sidebar: false, but there is stiil room for it on a big screen:
![image](https://user-images.githubusercontent.com/32191001/150987079-f1f765fa-cc6a-4a31-949c-d55256221867.png)

Is that how it should be?

/Morten

**Comment by frjo** [comment]
Should not be, do you have an URL to site or repo?

**Comment by frjo** [comment]
Found the url to the site in another issue. Do you have sidebar set to true in the page frontmatter maybe?

**Comment by mortenkjarulff** [comment]
https://gitlab.com/mortenkjarulff/gitte2

Ok, i did not set it to false, but did not set it at all. I tried once to set it to true, but removed the line again

**Comment by mortenkjarulff** [comment]
Setting it explicit to false did the trick 👍

**Comment by frjo** [comment]
For some reason I set if to default true, changed that in the 2.x branch now.
