### ISSUE TITLE
Question: How to use hugo-theme-zen with Hugo modules

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#54]
I haven't looked deeply into hugo modules to get and install themes as I am still using Zen them as submodule. Is it possible to use this them using hugo module system?

https://gohugo.io/hugo-modules/use-modules/

**Comment by frjo** [comment]
Yes, just as with any theme.

`hugo mod get -u github.com/frjo/hugo-theme-zen`

**Comment by arky** [comment]
Thanks @frjo
