### ISSUE TITLE
table body and head not aligned

### ISSUE THREAD

**Issue by jiacai2050** [frjo/hugo-theme-zen#61]
First, thanks for this awesome theme, I have used for quite a while. There is one annoying issue with table display, the head part isn't aligned with body, see figure below
<img width="616" alt="image" src="https://user-images.githubusercontent.com/3848910/175779081-1e06e986-46fd-4664-8b69-e1085ccdc12e.png">

Could you fix this? 

FYI, link below is my blog post with this issue
- https://emacstalk.github.io/post/017/

**Comment by frjo** [comment]
The "th" element is aligned "center" by default. The zen theme has no styles for this so fall back to the defaults implemented by the browser.

Sounds like you want it aligned "left" so add this style.

th {
  text-align: left;
}

The Zen theme is ment to be a base theme. A solid foundation with some neat features that you add your own design too.

It is of course perfectly fine to use it as is but  it do not look like much.

**Comment by jiacai2050** [comment]
Thanks
