### ISSUE TITLE
Max image width does not work when the sidebar is set to false

### ISSUE THREAD

**Issue by georgew509** [frjo/hugo-theme-zen#62]
I have these settings in my config.yaml file:

```
imageMaxWidth: 600
sidebar: false
```

I have noticed that the max image width is not working when sidebar is set to false. It works fine when set to true. [This is an example.](http://localhost:1313/posts/2021/a-new-year-and-a-new-host/) I currently have sidebar set to false. The actual image width is 1280. I know that I can set the desired width in the figure short code. But I would have to do that for every image.

I have also installed a notice short code that is using an SVG image for the background color, and I noticed that it is also expanding the beyond the 600 width.

**Comment by georgew509** [comment]
I forgot to mention that I am using page bundles, in case that makes a difference:

```
george@imac1:~/Hugo/apcom/content/posts/2021
$ tree a-new-year-and-a-new-host
a-new-year-and-a-new-host
├── images
│   └── new-years-eve-3882231_1280.jpg
└── index.md
```

**Comment by georgew509** [comment]
Some additional details (sorry that I didn't see this in the beginning).

The image on the home page is in the assets/images directory, and the max image width setting is working for it (image is 1200 pixels wide). I also noticed that the text on the home page is also expanding to the full page width, but the post text stays at about the 70 ch setting (I know, not the same issue).

**Comment by georgew509** [comment]
I am using the figure shortcode:

{{< figure src="images/new-years-eve-3882231_1280.jpg" alt="New Years image." attr="Image by [Gerd Altmann](https://pixabay.com/users/geralt-9301/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3882231) from [Pixabay](https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=3882231)." class="center" >}}

But the images is in a page bundle. Does that make a difference?

Thanks much,
George

**Comment by frjo** [comment]
The figure and img shortcodes support images in "static" and in "assets" directories.

They do not work with page bundles. See the Hugo forum for examples is my recommendation. Some other theme might have shortcodes that work with pae bundles as well, you could copy them.

They

**Comment by georgew509** [comment]
Thanks for reopening and replying.

I am still a bit confused. I am using the figure shortcode with page bundle images, and it seems to be working just fine. For example:

https://altoplace.com/macos/configure-apache-and-php-fpm-on-macos/

$ l content/macos/configure-apache-and-php-fpm-on-macos
images/   index.md

---

{{< figure src="images/apple-1868496_1280.png" alt="Apple Computer." attr="Image by [Pexels](https://pixabay.com/users/pexels-2286921/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1868496) from [Pixabay](https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=1868496)." class="center" >}}

**Comment by georgew509** [comment]
Got it. For now, I am moving all my images to the assets directory. I still have a lot to learn. Page bundles sounded like a neat idea. After trying several Hugo themes, I want to stick with the Zen theme for a solid base for performance and learning about Hugo. Thank you for your help.

**Comment by frjo** [comment]
Page bundles are really neat. I do not use them since they do not fit the workflow of my customers.
