### ISSUE TITLE
Provide a demo for the "Podcast" feature

### ISSUE THREAD

**Issue by RoneoOrg** [frjo/hugo-theme-zen#63]
Hi there,

I would like to see the [podcast feature](https://github.com/frjo/hugo-theme-zen#podcast) in action, but couldn't find a live demo, even with a check on every sites of [the section "Sites using the Hugo Zen theme" ](https://github.com/frjo/hugo-theme-zen#sites-using-the-hugo-zen-theme)

(A showcase of the shortcodes would be useful too)

Thanks!

**Comment by frjo** [comment]
Here is someone that are using the Zen theme for podcasting: https://gitte.one/podcast/

I should set up a demo site for this theme. Will try to get that done after the summer holiday, so earliest in September.

**Comment by frjo** [comment]
Rainy day so here we have a demo site: https://zen-demo.xdeb.org
