### ISSUE TITLE
Cover image for posts / pages

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#69]
Is there a way to add cover image for page or post. Is this currently supported by hugo-theme-zen by default. 

Would like to display the image in both [listing pages](https://dancing-tulumba-c1f460.netlify.app/posts/) and also [single post pages](https://dancing-tulumba-c1f460.netlify.app/posts/%E0%AC%9A%E0%AC%B2%E0%AC%95-%E0%AC%B9%E0%AC%B0%E0%AC%A6/).

**Comment by frjo** [comment]
There is no feature for that in the Zen them. I only add base functions that I need on more or less every site I build.

I suggest you copy `theme/zen/layouts/_default/single.html` and `theme/zen/layouts/_default/summary.html` to your root `layouts/_default/` and modify them to support cover images.

The Zen theme is not really ment to be used as is. I have created it to act as a solid base for every Hugo site I build for myself and for customers.

**Comment by arky** [comment]
Thank you @frjo . Closing this issue as resolved.
