### ISSUE TITLE
Enable wrapping text around images

### ISSUE THREAD

**Issue by arky** [frjo/hugo-theme-zen#76]
There seems to be no way wrap text around images in hugo-theme-zen. 

![image](https://user-images.githubusercontent.com/808895/216321151-10a4c957-61d1-46f9-bf0f-e76c6f1b771e.png)

https://dancing-tulumba-c1f460.netlify.app/en

https://dancing-tulumba-c1f460.netlify.app/en/book/watersil-paikhanara-byabahar-o-rakshanabekshana-1991/

**Comment by frjo** [comment]
Are you talking about setting float left/right on images? There are some examples in the _zen.scss files, look for img/figure and left/right/center.

Please remember that Zen is a base theme, not meant to be used as is. It is a foundation that you build your own house on, so to speak.

**Comment by frjo** [comment]
Replace the hyphen with a space and it should work, `class="image left"` on an "img" tag e.g.

For most customer sites I add an empty `/assets/sass/_zen.scss` to completely remove the styles.

**Comment by arky** [comment]
Ah! Thank you for spotting my mistake. 

I'll use `/assets/sass/_zen.scss`  to override the styles in future.
