### ISSUE TITLE
logo + mobile results on Lighthouse overlap warning

### ISSUE THREAD

**Issue by danielfdickinson** [frjo/hugo-theme-zen#79]
If one enables a 64x64 logo in params, then Lighthouse complains that the logo and and the mobile menu overlap (the warning is 'inappropriately sized tap targets' and details describe it as an overlap).

**Comment by frjo** [comment]
Thanks for the report, had missed that. Will see what I can do about it.

**Comment by frjo** [comment]
I have implemented a fix for Zen 3 now.

If you are using 2.x you can add this css to fix it I think.

```
.header {
  &__logo {
    width: fit-content;
  }
}
```

**Comment by frjo** [comment]
If you can confirm that it works I will make a new 2.x release with the fix.

**Comment by danielfdickinson** [comment]
I'm using v3, and it works. Thank you.

**Comment by danielfdickinson** [comment]
Er, actually there may be a regression with the .header .layout__header -- I ended up with an all black header (couldn't see title), until I used:
```css
header.layout__header {
  background-color: inherit;
}
```

in `_extra.scss`. I'm not sure if that is because of my overrides, or an issue with the update.

**Comment by frjo** [comment]
I think that is due to a change I made in `assets/sass/components/header/_header.scss`:

~~~~
.header,
%header {
  …
  background-color: var(--color-header-bg);
  …
}
~~~~

**Comment by danielfdickinson** [comment]
Thank you; sorry for taking so long to get back to you. It's taken me a while to get to testing the changes because of how I was using the theme.

I'm now planning to have a second fork of this repo in which I have the collection of all my changes, and the first is the one I already have, which tracks this repo and I use for things in which I think you may have an interest. The main reason for the second repo is laziness on my part; I'm using modifications to the theme in three different sites.

Thank you for all your hard work, and I hope I can have some changes that you find worth your while.

**Comment by danielfdickinson** [comment]
Thank you; sorry for taking so long to get back to you. I'm planning to have a second fork of this repo in which I have the collection of all my changes, and the first is the one I already have, which tracks this repo and I use for things in which I think you may have an interest. The main reason for the second repo is laziness on my part; I'm using modifications to the theme in three different sites, and it is a lot easier to keep them in sync if I have 'my own' fork

**Comment by danielfdickinson** [comment]
Sorry, I guess I didn't say, it works once I make all the changes.
