### ISSUE TITLE
`assets/vendor` missing when using theme as a module

### ISSUE THREAD

**Issue by danielfdickinson** [frjo/hugo-theme-zen#85]
Unfortunately, a directory named `vendor` causes problems for Hugo modules due to the way Go modules work. This was discussed on the forum in context of PHP, but I discovered it also affects this folder as well. In DFD-Zen I have renamed the folder and all works the way it should. See: 

https://discourse.gohugo.io/t/is-it-still-true-due-to-the-way-go-works-that-one-should-not-use-a-vendor-folder-in-a-hugo-project/38899

**Comment by frjo** [comment]
Thanks for the heads up, will implement a fix.

**Comment by frjo** [comment]
Opted to rename it "libs", I might put other things that js files there in the future.
