### ISSUE TITLE
Responsive table JS not working on Microsoft Edge 112

### ISSUE THREAD

**Issue by danielfdickinson** [frjo/hugo-theme-zen#88]
https://github.com/frjo/hugo-theme-zen/commit/a5e759d988da5ed4071ac575c4253e8e9bd056f0#r110247012

For me, on Microsoft Edge 112 `'tr:has(td)'` doesn't work, but using `'tbody tr'` does.

I also see [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) that `:has` is not supported on Firefox without manual enablement by user and not at all on Firefox for Android.

**Comment by frjo** [comment]
And I who really like the new ":has()" selector :-). Made some changes now, can you confirm it fixes the issue?

Checked https://caniuse.com/?search=%3Ahas and it should work for Edge but not always apparently.

**Comment by danielfdickinson** [comment]
That works on Edge quite well...Unfortunately it does not work on Firefox.

**Comment by frjo** [comment]
Oops, I realised I missed that the js is using `:has()` as well. Fixed now.

**Comment by danielfdickinson** [comment]
It's solved. Thank you.
