### ISSUE TITLE
Problem with syntax highlighting

### ISSUE THREAD

**Issue by ummels** [frjo/hugo-theme-zen#90]
Hi,

when formatting a code block with Hugo's standard syntax highlighting, some of the code is barely readable due to the foreground colour being too dark.

[Example blog post demonstrating the issue](https://ummels.github.io/zen-test/blog/post-0/)

I guess, the issue stems from the fact that `_reset.scss` sets the foreground colour for `code` elements, but Hugo's syntax highlighting sets the foreground color on the surrounding `pre` element.

**Comment by frjo** [comment]
Thanks for reporting this issue!

I have attempted a fix in commit [79ad438](https://github.com/frjo/hugo-theme-zen/commit/79ad438b19f633855b9bc861b88e96243b3ad4c1).

Setting colour should never have been in "reset". Now moved to "base" and I avoid setting colour on code with syntax highlighting by using "code:not([data-lang])".

Please report back if this fixes your issue.

**Comment by ummels** [comment]
Thanks al lot! This fixes the issue indeed.
